Equalização do projeto
arthurmdros/FlexConC pull request #19
Opened 2024-11-13 23:20 UTC by LuizMiguel4444

Foi feito a equalização do projeto para manter apenas uma branch que tem sentido.

2024-11-25 02:12 UTC, ArthurGorgonio requested changes
@LuizMiguel4444, o código está bom, seria bom você dar uma avaliada em algumas sugestões que deixei no MR. Tem umas que são obrigatórias e outras opcionais. Divida o trabalho com @RenanCDev e @josealvs.

2024-11-25 02:12 UTC, ArthurGorgonio commented on .github/workflows/unittest.yml
> +        python-version: ["3.9", "3.10"]
```suggestion
        python-version: ["3.10", "3.12"]
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +import pandas as pd
por que?

não seria melhor utilizar o from pandas import «função que você precisa»?

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +init_labelled = [0.03, 0.05, 0.08, 0.1, 0.13, 0.15, 0.18, 0.2, 0.23, 0.25]
Num bagunça, deixa explícito e padronizado em relação aos outros
```suggestion
init_labelled = [0.03, 0.05, 0.08, 0.10, 0.13, 0.15, 0.18, 0.20, 0.23, 0.25]
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +    comite = "Comite_Naive_" if args.classifier == 1 else "Comite_Tree_" if args.classifier == 2 else 'Comite_KNN_' if args.classifier == 3 else "Comite_Heterogeneo_"
linha muito grande :eyes:, resolvam sem usar if-elif-else.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                        exit()
esse if está no canto errado, né?

move para a linha ~26, não faz sentido seguir com o código se vc já sabe que o classificador num vai dar bom.

~Isso vai sair se a gente for transformar em lib, mas ok...~

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                            print(f"\n\nO sistema irá selecionar instâncias da base {dataset}. Para o treinamento, será usado {round(labelled_level, 4) * 100}% das instâncias rotuladas de um total de
para que é utilizada essa `flag`? Se num tiver sendo utilizada, mata ela. Se for com o intuito de informar algo, colocar antes de iterar nos Folds, acho que faz mais sentido.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +parser.add_argument('classifier', metavar='c', type=int, help='Escolha um classificador para criar um cômite. Opções: 1 - Naive Bayes, 2 - Tree Decision, 3 - Knn, 4 - Heterogeneous')
limite maior que 79 chars, PEP8.
se ligar um pylint da vida ele vai reclamar.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +
Linha com identação, sem código (em branco). Remover.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +
Linha com identação, sem código (em branco). Remover.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                f'"DATASET","LABELLED-LEVEL","ACC-AVERAGE","STANDARD-DEVIATION-ACC","F1-SCORE-AVERAGE","STANDARD-DEVIATION-F1-SCORE"'
limite maior que 79 chars, PEP8.
se ligar um pylint da vida ele vai reclamar.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                    y_train, y_test = _target_unlabelled[train], _target_unlabelled[test]
limite maior que 79 chars, PEP8.
se ligar um pylint da vida ele vai reclamar.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                        print('\nOpção inválida! Escolha corretamente...\nOpções: 1 - Naive Bayes, 2 - Tree Decision, 3 - Knn, 4 - Heterogeneous\nEx: python main.py 1\n')
Esse if tá todo errado...
a melhor forma seria:


```suggestion
                    if args.classifier <= 4 and args.classifier > 0:
                        print(
                            '\nOpção inválida! Escolha corretamente...\nOpções'
                            ': 1 - Naive Bayes, 2 - Tree Decision, 3 - Knn, 4 '
                            '- Heterogeneous\nEx: python main.py 1\n'
                        )

```

e mesmo assim, este não é o melhor local para esse IF, deveria ser por volta da linha 26 quando vc já sabe o que o usuário informou no parser.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                            print(f"\n\nO sistema irá selecionar instâncias da base {dataset}. Para o treinamento, será usado {round(labelled_level, 4) * 100}% das instâncias rotuladas de um total de
Não faz sentido esse if com essa flag, mover esse print para um outro local que faça sentido. Que tal antes do `for train, test in kfold.split(_instances, _target_unlabelled):`?

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                        tInstanciasRotPCento = " Uso: " + str(instanciasRotPCento) + "% das Inst. Rot."
não é usado, mata
```suggestion
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                            comite.fit_ensemble(X_train, y)
Repensar essa estratégia aqui, tá verboso e complexo _e feio :eyes:_

`y = ut.select_labels(y_train, X_train, labelled_instances)` e `comite.fit_ensemble(X_train, y)` são linhas de código que se repetem, será que num dá para fazer de outra forma?

Ainda tem um erro de lógica aqui.... os comitês estão BEM esquisitos. Alinhar com Karliane de como será o comitê, mas do jeito do código o comitê tem... ~29~30 classificadores, a comparação está injusta.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +                        result_acc = round(accuracy_score(y_test, y_pred) * 100, 4)
tira esse caba aqui, deixa para fazer round e multiplicar depois. salva o número cru (raw) mesmo, pq se precisar aumentar as casas decimais para ver quem ganhou no empate técnico a gente consegue avaliar isso.

2024-11-25 02:12 UTC, ArthurGorgonio commented on main.py
> +import src.utils as ut
evitar fazer isso, pois pode ser que você acabe escolhendo 'sem querer' um nome que já é utilizado pelo python (exemplo ssl, que é uma lib para tratar certificados encriptados). Então, prefira fazer `from utils import calculateMeanStdev, select_labels, ...`

2024-11-25 02:12 UTC, ArthurGorgonio commented on requirements.txt
> +# pushbullet==0.1
Suspeito :suspect: :detective:

2024-11-25 02:12 UTC, ArthurGorgonio commented on requirements.txt
>  sklearn==0.0
ué?

2024-11-25 02:12 UTC, ArthurGorgonio commented on requirements.txt
>  mock==4.0.3
remover

2024-11-25 02:12 UTC, ArthurGorgonio commented on requirements.txt
Revisar esse arquivo todo e ver quais imports a gente está realmente utilizando.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/co_flexcon.py
> +
faltou pep (add mais uma linha em branco antes da declaração da classe)

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
> +    def __init__(self, ssl_algorithm: callable, **kwargs):
```suggestion
    def __init__(self, ssl_algorithm: callable, **kwargs) -> None:
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
>      def add_classifier(self, classifier):
```suggestion
    def add_classifier(self, classifier) -> None:
```

colocar o tipo o argumento "classifier".

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
> +    def add_model(self, model):
```suggestion
    def add_model(self, model) -> None:
```
Add tipo do argumento.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
>      def remover_classifier(self, classifier):
```suggestion
    def remover_classifier(self, classifier) -> None:
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
> +    def measure_classifier(self, instances) -> list:
qual o tipo de instances?

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
>      def drop_ensemble(self):
```suggestion
    def drop_ensemble(self) -> None:
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
> +    def fit_ensemble(self, instances, classes):
```suggestion
    def fit_ensemble(self, instances, classes) -> None:
```
tipos de instance e classes

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
> +    def fit_single_classifier(self, classifier, instances, classes):
```suggestion
    def fit_single_classifier(self, classifier, instances, classes) -> ???:
```

tipos das variáveis.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
>      def predict_one_classifier(self, classifier, instances):
```suggestion
    def predict_one_classifier(self, classifier, instances) -> ???:
```
tipos das variáveis

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/ensemble.py
>      def predict(self, instances):
```suggestion
    def predict(self, instances) -> ???:
```

tipos das variáveis

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
> +        self.size_y: int = 0
??

Atributo está solto. Não é utilizado em canto nenhum.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
> +        self.validate()
a ideia da função está OK, mas não precisa estar no `src.utils`, talvez seja melhor estar na classe mesmo. Por ser requisito da aplicação.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
> -
Esse método aqui poderia ter deixado, ele aparece no `print(BaseFlexConC())`.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
> +        ...
![image](https://github.com/user-attachments/assets/f80753cc-821b-4521-ad83-3dbb8741b4e3)
![image](https://github.com/user-attachments/assets/c63acd45-e4b6-4eef-a8ec-b0ca83857da7)

```suggestion
        raise NotImplementedError('Implement me')
```

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
> +        return True
Esse método é o método certo. Trazer a função `validate_estimator` para cá.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +    KNN(n_neighbors=5, weights='distance'),KNN(n_neighbors=5)]
Coloca um espaço ou quebra a linha, daí fica top

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +    KNN(n_neighbors=5, weights='distance'),KNN(n_neighbors=5)]
Coloca um espaço ou quebra a linha, daí fica top.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +    KNN(n_neighbors=6, weights='distance'),KNN(n_neighbors=6)]
Coloca um espaço ou quebra a linha, daí fica top.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +
Coloca um espaço ou quebra a linha, daí fica top.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +        print("Please put a number > 2")
Me parece desnecessária essa função, tenho a vaga lembrança da lib do scikit learning já fazer essa validação para a gente.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +    return y_train
Essa função tá muito zoada, será refatorada na #20, junto da quebra dos unitários. Dando uma palhinha do que vocês tem que fazer:
- contar quantas instâncias por classe existem (bincount do numpy resolve o problema);
- quantidade mínima de instâncias por classe, então é MAX(1, QTD_CLASSES * percentual rotulado);
- selecionar com o np.random.choice (linhas 80~82, ainda será necessário alterar uma coisa);
- Linhas 89 até a 92 estão certas.

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +        return f1
Refatorar essa função

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/utils.py
> +            )
Refatorar essa função também

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
> -
Volta com esses linhas aqui, elas dão infos úteis do método (verbose) e indica a condição de terminação kk

2024-11-25 02:12 UTC, ArthurGorgonio commented on src/ssl/flexcon.py
>          """
Voltar com as linhas que fizerem sentido.

2024-12-24 02:30 UTC, LuizMiguel4444 commented on .github/workflows/unittest.yml
> +        python-version: ["3.9", "3.10"]
feito

2024-12-24 02:32 UTC, LuizMiguel4444 commented on main.py
> +import pandas as pd
feito

2024-12-24 02:34 UTC, LuizMiguel4444 commented on main.py
> +init_labelled = [0.03, 0.05, 0.08, 0.1, 0.13, 0.15, 0.18, 0.2, 0.23, 0.25]
feito

2024-12-24 02:39 UTC, LuizMiguel4444 commented on main.py
> +    comite = "Comite_Naive_" if args.classifier == 1 else "Comite_Tree_" if args.classifier == 2 else 'Comite_KNN_' if args.classifier == 3 else "Comite_Heterogeneo_"
feito

2024-12-24 02:45 UTC, LuizMiguel4444 commented on main.py
> +                        exit()
feito

2024-12-24 02:48 UTC, LuizMiguel4444 commented on main.py
> +                            print(f"\n\nO sistema irá selecionar instâncias da base {dataset}. Para o treinamento, será usado {round(labelled_level, 4) * 100}% das instâncias rotuladas de um total de
feito

2024-12-24 02:53 UTC, LuizMiguel4444 commented on main.py
> +parser.add_argument('classifier', metavar='c', type=int, help='Escolha um classificador para criar um cômite. Opções: 1 - Naive Bayes, 2 - Tree Decision, 3 - Knn, 4 - Heterogeneous')
feito

2024-12-24 03:03 UTC, LuizMiguel4444 commented on main.py
> +
feito

2024-12-24 03:03 UTC, LuizMiguel4444 commented on main.py
> +
feito

2024-12-24 03:17 UTC, LuizMiguel4444 commented on main.py
> +                f'"DATASET","LABELLED-LEVEL","ACC-AVERAGE","STANDARD-DEVIATION-ACC","F1-SCORE-AVERAGE","STANDARD-DEVIATION-F1-SCORE"'
feito

2024-12-24 03:18 UTC, LuizMiguel4444 commented on main.py
> +                    y_train, y_test = _target_unlabelled[train], _target_unlabelled[test]
feito

2024-12-24 03:31 UTC, LuizMiguel4444 commented on main.py
> +                        print('\nOpção inválida! Escolha corretamente...\nOpções: 1 - Naive Bayes, 2 - Tree Decision, 3 - Knn, 4 - Heterogeneous\nEx: python main.py 1\n')
feito

2024-12-24 03:32 UTC, LuizMiguel4444 commented on main.py
> +                            print(f"\n\nO sistema irá selecionar instâncias da base {dataset}. Para o treinamento, será usado {round(labelled_level, 4) * 100}% das instâncias rotuladas de um total de
feito

2024-12-24 03:33 UTC, LuizMiguel4444 commented on main.py
> +                        tInstanciasRotPCento = " Uso: " + str(instanciasRotPCento) + "% das Inst. Rot."
feito

2024-12-27 01:06 UTC, ArthurGorgonio commented
ops... :eyes: errei uma config aqui haha. Ignorem as _n_ notificações, é pq eu fui arrumar uma parada no CI, para não ficar ativando direto, só que aproveitei para padronizar outras coisas.

@LuizMiguel4444, @RenanCDev e @josealvs.

2024-12-30 18:01 UTC, LuizMiguel4444 commented on main.py
> +                            comite.fit_ensemble(X_train, y)
feito

2024-12-30 18:02 UTC, LuizMiguel4444 commented on main.py
> +                            comite.fit_ensemble(X_train, y)
@ArthurGorgonio pq 30 classificadores ?? Não consigo enxergar 👀

2024-12-30 18:16 UTC, LuizMiguel4444 commented on main.py
> +                        result_acc = round(accuracy_score(y_test, y_pred) * 100, 4)
feito

2024-12-30 18:21 UTC, LuizMiguel4444 commented on main.py
> +import src.utils as ut
feito

2024-12-30 18:21 UTC, LuizMiguel4444 commented on requirements.txt
> +# pushbullet==0.1
feito

2024-12-30 18:22 UTC, LuizMiguel4444 commented on requirements.txt
>  sklearn==0.0
feito

2024-12-30 18:22 UTC, LuizMiguel4444 commented on requirements.txt
>  mock==4.0.3
feito

2024-12-30 18:23 UTC, LuizMiguel4444 commented on src/ssl/co_flexcon.py
> +
feito

2024-12-30 18:24 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
> +    def __init__(self, ssl_algorithm: callable, **kwargs):
feito

2024-12-30 18:25 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
>      def add_classifier(self, classifier):
feito

2024-12-30 18:25 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
> +    def add_model(self, model):
feito

2024-12-30 18:26 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
>      def remover_classifier(self, classifier):
feito

2024-12-30 18:26 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
> +    def measure_classifier(self, instances) -> list:
feito

2024-12-30 18:27 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
>      def drop_ensemble(self):
feito

2024-12-30 18:27 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
> +    def fit_ensemble(self, instances, classes):
feito

2024-12-30 18:37 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
> +    def fit_single_classifier(self, classifier, instances, classes):
feito

2024-12-30 18:37 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
>      def predict_one_classifier(self, classifier, instances):
feito

2024-12-30 18:37 UTC, LuizMiguel4444 commented on src/ssl/ensemble.py
>      def predict(self, instances):
feito

2024-12-30 18:38 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
> +        self.size_y: int = 0
feito

2024-12-30 18:46 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
> +        self.validate()
feito

2024-12-30 18:47 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
> -
feito

2024-12-30 18:49 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
> +        ...
feito

2024-12-30 18:51 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
> +        return True
feito

2024-12-30 18:55 UTC, LuizMiguel4444 commented on src/utils.py
> +    KNN(n_neighbors=5, weights='distance'),KNN(n_neighbors=5)]
feito

2024-12-30 18:55 UTC, LuizMiguel4444 commented on src/utils.py
> +    KNN(n_neighbors=5, weights='distance'),KNN(n_neighbors=5)]
feito

2024-12-30 18:55 UTC, LuizMiguel4444 commented on src/utils.py
> +    KNN(n_neighbors=6, weights='distance'),KNN(n_neighbors=6)]
feito

2024-12-30 18:55 UTC, LuizMiguel4444 commented on src/utils.py
> +
feito

2024-12-30 18:56 UTC, LuizMiguel4444 commented on src/utils.py
> +        print("Please put a number > 2")
feito

2024-12-30 18:57 UTC, LuizMiguel4444 commented on src/utils.py
> +    return y_train
feito

2024-12-30 19:22 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
> -
feito

2024-12-30 19:22 UTC, LuizMiguel4444 commented on src/ssl/flexcon.py
>          """
feito

2024-12-30 19:24 UTC, LuizMiguel4444 commented on src/utils.py
> +    return y_train
feito

2024-12-30 19:33 UTC, LuizMiguel4444 commented on src/utils.py
> +        return f1
feito

2024-12-30 19:33 UTC, LuizMiguel4444 commented on src/utils.py
> +            )
feito

2025-01-07 03:27 UTC, ArthurGorgonio approved these changes
Agora está tudo certo. Parabéns pelas alterações.

2025-01-07 03:32 UTC, merged